name: Build and Deploy to Sandbox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8
        
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.6.3
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        echo "<settings>
          <servers>
            <server>
              <id>anypoint-exchange-v3</id>
              <username>${{ secrets.ANYPOINT_PLATFORM_USERNAME }}</username>
              <password>${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}</password>
            </server>
            <server>
              <id>mulesoft-releases</id>
              <username>${{ secrets.ANYPOINT_PLATFORM_USERNAME }}</username>
              <password>${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}</password>
            </server>
          </servers>
          <profiles>
            <profile>
              <id>mule-extra-repos</id>
              <activation>
                <activeByDefault>true</activeByDefault>
              </activation>
              <repositories>
                <repository>
                  <id>central</id>
                  <name>Maven Central</name>
                  <url>https://repo.maven.apache.org/maven2/</url>
                  <layout>default</layout>
                </repository>
                <repository>
                  <id>mulesoft-releases</id>
                  <name>MuleSoft Repository</name>
                  <url>https://repository.mulesoft.org/releases/</url>
                  <layout>default</layout>
                </repository>
                <repository>
                  <id>anypoint-exchange-v3</id>
                  <name>Anypoint Exchange V3</name>
                  <url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
                  <layout>default</layout>
                </repository>
              </repositories>
              <pluginRepositories>
                <pluginRepository>
                  <id>mulesoft-releases</id>
                  <name>MuleSoft Repository</name>
                  <url>https://repository.mulesoft.org/releases/</url>
                  <layout>default</layout>
                </pluginRepository>
              </pluginRepositories>
            </profile>
          </profiles>
        </settings>" > ~/.m2/settings.xml
        
    - name: Clean Maven local repository
      run: |
        rm -rf ~/.m2/repository/org/mule/tools/maven
        rm -rf ~/.m2/repository/org/eclipse/aether
        
    - name: Build with Maven
      run: mvn -B clean package -DskipTests
      env:
        MAVEN_OPTS: "-Xmx2048m"
        
    - name: Deploy to CloudHub 2.0
      run: |
        mvn deploy -DmuleDeploy -DskipTests -DskipDeploymentVerification=true \
        -Danypoint.username="${{ secrets.ANYPOINT_PLATFORM_USERNAME }}" \
        -Danypoint.password="${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}" \
        -Dencryption.key="${{ secrets.ENCRYPTION_KEY }}"
      env:
        MAVEN_OPTS: "-Xmx2048m"